services:
  mysql:
    image: mysql:8
    container_name: mysql_v1
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - newMySqlVolume:/var/lib/mysql

  web:
    image: avitd27/my-app:${TAG}
    container_name: flask_app_v3
    env_file:
      - .env
    ports:
      - "8080:5000"
    depends_on:
      - mysql

volumes:
  newMySqlVolume:
