services:
  mysql:
    image: mysql:8
    container_name: mysql_v1
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - newMySqlVolume:/var/lib/mysql

  flask-app-1:
    image: avitd27/my-app:latest
    container_name: flask_app_1
    ports:
      - "8001:8000"
    environment:
      - INSTANCE_NAME=flask-app-1
      - VERSION=500.0
    depends_on:
      - mysql
    restart: always

  flask-app-2:
    image: avitd27/my-app:latest
    container_name: flask_app_2
    ports:
      - "8002:8000"
    environment:
      - INSTANCE_NAME=flask-app-2
      - VERSION=1.0
    depends_on:
      - mysql
    restart: always

volumes:
  newMySqlVolume:
