version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql_v1
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - newMySqlVolume:/var/lib/mysql

  web:
    image: avitd27/myapp:v2
    container_name: flask_app_v1
    ports:
      - "8080:80"

volumes:
  newMySqlVolume:
  web_content: