name: Build and Deploy Flask App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Write Name
        run: echo "Trithikraj Doorga"